name : veekshithdev.js CI

on:
  push:
    branches:[master]
  pull request:
    branches:[master]

jobs:
  build:
    runs-on: self-hosted

  steps:
  - uses: actions/checkout@v2
  - name: Use node.js ${{matrix.node-version}}
    uses: actions/setup-node@v1
    with:
      node-version: ${{matrix.node-version}}
  - run:
      npm install
      npm run build
      
